
replicaCount: 1

image:
  repository: ramasubramanian06/go-web-app
  pullPolicy: IfNotPresent
  tag: "34322282158"

ingress:
  enabled: false
  className: ""
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
